name: no_controller
out_dir: "./reports"
n_eval_runs: 1
data:
  data_format: csv
  datasets:
    - name: "summer"
      house_data_file: "./data/benchmark/0080E1FA00236634.csv"
    - name: "autumn"
      house_data_file: "./data/benchmark/0080E1FA00236638.csv"
    - name: "spring"
      house_data_file: "./data/benchmark/0080E1FA00237198.csv"
  price_data_file: null
model:
  name: 'no_controller'
environment:
  battery:
    efficiency: 0.95
    capacity: 20000
    max_power: 8000
  scaling_method: "none"
  random_time_init: false
  init_time: 1514847600  # 1514761200+86400
  episode_length: 8290800 # 8463600-2*24*3600
  action_space_type: 'continuous'
  tax: 20
  dataset_args:
    building: "opsd_building_6"
    price: "germany"