name: mpc_perfect
out_dir: ./reports
n_eval_runs: 1
data:
  data_format: csv
  datasets:
    - name: "summer"
      house_data_file: "./data/benchmark/0080E1FA00236634.csv"
    - name: "autumn"
      house_data_file: "./data/benchmark/0080E1FA00236638.csv"
    - name: "spring"
      house_data_file: "./data/benchmark/0080E1FA00237198.csv"
  price_data_file: null
model:
  name: 'mpc'
  mpc_type: 'perfect'
  prediction_length: 96
environment:
  battery:
    efficiency: 0.95
    capacity: 20000
    max_power: 8000
  scaling_method: "none"
  random_time_init: false
  init_time: null
  episode_length: 86400
  action_space_type: 'continuous'
  tax: 20
  prediction_horizon: null
  dataset_args: null