name: rule_based
out_dir: ./reports
data:
  data_format: csv
  datasets:
    - name: "summer"
      house_data_file: "./data/benchmark/0080E1FA00236634.csv"
    - name: "autumn"
      house_data_file: "./data/benchmark/0080E1FA00236638.csv"
    - name: "spring"
      house_data_file: "./data/benchmark/0080E1FA00237198.csv"
  price_data_file: null
environment:
  action_space_type: continuous
  battery:
    capacity: 20000
    efficiency: 0.95
    max_power: 8000
  dataset_args:
    building: "summer"
    price: "summer"
  episode_length: 86400
  random_time_init: false
  scaling_method: none
  tax: 20
model:
  name: base
n_eval_runs: 1
